### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ammarahm-ed** [ammarahm-ed/react-native-admob-native-ads#9]
So finally it is here, proper Admob Native ads support for React Native. Still there are somethings that need to be done. I will make sure that I can support this long term however I would love if you would like to contribute to any part of this library.

- [x]  Complete Ad Creation and Customization Support
- [ ]  Ad Preloading: **WIP** [ad-preloading-patch branch](https://github.com/ammarahm-ed/react-native-admob-native-ads/tree/ad-preloading-patch)
- [ ]  Built-in ready-to-use customizable templates for NativeAdInterstital, NativeAdBanner and NativeAdMedium.

**Comment by ashishfeels** [comment]
@ammarahm-ed  thanks man i was looking for this , tried the react native admob but this seems more interesting and fine.

**Comment by ammarahm-ed** [comment]
@ashishfeels Thank you! feel free to open suggestions or issues if you face a problem. react-native-admob is not actively mantained. This is however.

**Comment by ashishfeels** [comment]
yes @ammarahm-ed  can you just look what im doing wrong the ads are not getting displayed as intended

**Comment by ammarahm-ed** [comment]
you can find me on discord under the username ammarahm-ed

**Comment by ashishfeels** [comment]
> you can find me on discord under the username ammarahm-ed

the four-digit tag is missing.

**Comment by ammarahm-ed** [comment]
ammarahm-ed#3680

and you need to update to the latest version of this library. It appears that you are using the old version. And send screenshots only from the example app so I can test it here.

**Comment by ashishfeels** [comment]
i just installed this from npm v0.2.4 , i will try it once more. also i tried to run the example app but it didn't ran , also i have sent you a request on discord.

**Comment by mrousavy** [comment]
@ammarahm-ed your approach by setting the Ads to a global instance and fetching those in your NativeAd View is not typical for native modules, is there a reason you're doing that instead of e.g. fetching an Ad which is literally a variable in JS (state) and then passing that in your JSX to the NativeAd view? Would make more sense to me and give more control over the Ads.

```ts
const [ad, setAd] = useState(null);
const load = useCallback(() => {
  const _ad = AdManager.loadAd(...);
  setAd(_ad);
}, []);
// call load every minute or so
```

Or with a hook approach:
```ts
// this gets automatically updated every minute or so. Configuration can be passed as arguments
const ad = useNativeAds();
// ...
<NativeAd ad={ad} ...
```

Just some thoughts. I'd gladly help out with development after my current side project 😄

**Comment by ammarahm-ed** [comment]
@mrousavy We are using React Context because we need the native ad information in all the child views that the user of library will add. Using context makes it simple to pass that information around in state and update it dynamically.

**Comment by mrousavy** [comment]
@ammarahm-ed what native ad information are we talking about here?

**Comment by ammarahm-ed** [comment]
Everything from text to images.

**Comment by ammarahm-ed** [comment]
closing this issue
